# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "validators-prometheus-scrape"
version = "0.1.0"
description = "Validator for prometheus_scrape interface"
authors = [
    {name = "SQA Team", email = "solutionsqa@canonical.com"}
]

requires-python = ">=3.10"
dependencies = [
    "validators-base",
]

[project.entry-points."endpoint_validators"]
prometheus_scrape = "validators.prometheus_scrape:PrometheusScrapeValidator"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["validators.prometheus_scrape"]

[tool.setuptools.package-dir]
"validators.prometheus_scrape" = "."
