# Copyright 2024-2025 Canonical Ltd.
# See LICENSE file for licensing details.

import re
from typing import Any


def _convert_to_string(value: Any) -> str:
    """Convert a value to a string.

    Args:
        value: The value to convert (can be bytes, str, or any object)

    Returns:
        String representation of the value
    """
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return str(value)


def _normalize_numeric_sequences(text: str) -> str:
    """Replace all numeric sequences with 'XXX'.

    This normalizes timestamps, IP addresses, and other variable numeric data.

    Args:
        text: The text to normalize

    Returns:
        Text with all numeric sequences replaced
    """
    return re.sub(r"\d+", "XXX", text)


def _normalize_pod_names(text: str) -> str:
    """Normalize Kubernetes pod names to remove dynamic suffixes.

    Pod names in Kubernetes logs often appear as pod=<podName>_<namespace>(<uid>)
    This function replaces the entire pod reference with pod=XXX.
    See: https://github.com/canonical/kubernetes-dqlite/blob/136e88e2c4309776ff735a990003ecb5e541dc94/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L925
    See: https://github.com/kubernetes/kubernetes/blob/df11db1c0f08fab3c0baee1e5ce6efbf816af7f1/pkg/kubelet/util/format/pod.go#L36

    Args:
        text: The text containing pod names

    Returns:
        Text with pod references normalized
    """
    return re.sub(
        r"pod=[a-z0-9.-]+_[a-z0-9.-]+\([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\)",
        "pod=XXX",
        text,
    )


def _normalize_uuids(text: str) -> str:
    """Replace UUIDs with 'XXX'.

    Matches standard UUID format: 8-4-4-4-12 hex digits.

    Args:
        text: The text containing UUIDs

    Returns:
        Text with UUIDs replaced
    """
    return re.sub(r"[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}", "XXX", text)


def _normalize_temp_files(text: str) -> str:
    """Normalize temporary file paths with random suffixes.

    Matches patterns like /tmp<alphanumeric> (e.g., /tmp5d7rg3qj, /tmp_test123)
    commonly generated by mkstemp and similar functions.

    Args:
        text: The text containing temp file paths

    Returns:
        Text with temp file suffixes normalized
    """
    return re.sub(r"/tmp[a-zA-Z0-9_]+", "/tmpXXX", text)


def _normalize_minio_probe_urls(text: str) -> str:
    """Normalize MinIO probe-bsign URLs with random nonces.

    MinIO health checks use probe-bsign-<random> patterns for authentication
    and connectivity testing. This normalizes these URLs for consistent metadata.

    Args:
        text: The text containing MinIO probe URLs

    Returns:
        Text with probe-bsign nonces normalized
    """
    return re.sub(r"probe-bsign-[a-z0-9]+", "probe-bsign-XXX", text)


def _normalize_oci_image_digests(text: str) -> str:
    """Normalize OCI image digests.

    OCI/Docker images use digests matching this grammar:
      digest                ::= algorithm ":" encoded
      algorithm             ::= algorithm-component (algorithm-separator algorithm-component)*
      algorithm-component   ::= [a-z0-9]+
      algorithm-separator   ::= [+._-]
      encoded               ::= [a-zA-Z0-9=_-]+

    Only matches registered algorithms: sha256, sha512, blake3

    See: https://github.com/opencontainers/image-spec/blob/main/descriptor.md#digests
    See: https://github.com/opencontainers/image-spec/blob/main/descriptor.md#registered-algorithms

    Args:
        text: The text containing OCI image references

    Returns:
        Text with image digests normalized
    """
    return re.sub(r"((?:sha256|sha512|blake3)(?:[+._-][a-z0-9]+)*):[a-zA-Z0-9=_-]+", r"\1:XXX", text)


def _truncate_string(text: str, max_length: int) -> str:
    """Truncate a string to a maximum length.

    Args:
        text: The text to truncate
        max_length: Maximum character count (default: 150)

    Returns:
        Truncated text with ellipsis if needed
    """
    if len(text) > max_length:
        return f"{text[:max_length - 3]}..."
    return text


def normalize_string(message: Any, max_length: int = 150) -> str:
    """Normalize a string for use as execution metadata.

    Applies multiple normalizations to create consistent metadata across test runs:
    - Converts bytes/objects to strings
    - Normalizes Kubernetes pod names
    - Normalizes UUIDs
    - Normalizes temporary file paths
    - Normalizes MinIO probe URLs
    - Normalizes OCI image digests
    - Replaces all numeric sequences
    - Truncates to maximum length

    Args:
        message: The value to normalize (can be bytes, str, or any object)

    Returns:
        Normalized string suitable for execution metadata
    """
    text = _convert_to_string(message)
    text = _normalize_pod_names(text)
    text = _normalize_uuids(text)
    text = _normalize_temp_files(text)
    text = _normalize_minio_probe_urls(text)
    text = _normalize_oci_image_digests(text)
    text = _normalize_numeric_sequences(text)
    text = _truncate_string(text, max_length)
    return text
