# Copyright (C) 2025 Canonical Ltd

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[project]
name = "bundle-builder"
version = "0.1.2"
description = "Framework to generate Juju compatible bundles from charmhub."
authors = [
    {name = "SQA Team",email = "solutionsqa@canonical.com"}
]

requires-python = ">=3.10"
dependencies = [
    "pyyaml>=6.0.1",
    "requests",
    "pydantic (>=2.11.3,<3.0.0)",
    "pytest-timeout>=2.3.1",
]

[tool.poetry]
packages = [
    { include = "bundle_builder" },
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
bundle-builder = "bundle_builder.entrypoint:main"
