[project]
name = "charm-integration-testing-meta"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.10,<4.0"


[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
charm-integration-testing = { path = "./charm_integration_testing", develop = true }
bundle-builder-x = { path = "./bundle_builder_x", develop = true }
validators-base = { path = "./validators/base", develop = true }
validators-test-utils = { path = "./validators/test_utils", develop = true }
validators-runner = { path = "./validators/runner", develop = true }
validators-postgresql-client = { path = "./validators/postgresql_client", develop = true, extras = ["dev", "deep", "uat"] }
validators-pgsql = { path = "./validators/pgsql", develop = true, extras = ["dev"] }
validators-mongodb-client = { path = "./validators/mongodb_client", develop = true }
validators-mysql-client = { path = "./validators/mysql_client", develop = true, extras = ["dev"] }
validators-mysql = { path = "./validators/mysql", develop = true, extras = ["dev"] }
validators-tracing = { path = "./validators/tracing", develop = true, extras = ["dev", "deep", "uat"] }
validators-prometheus-scrape = { path = "./validators/prometheus_scrape", develop = true }
validators-s3 = { path = "./validators/s3", develop = true }
validators-loki-push-api = { path = "./validators/loki_push_api", develop = true }
validators-temporal-host-info = { path = "./validators/temporal_host_info", develop = true }
validators-object-storage = { path = "./validators/object_storage", develop = true }
validators-kafka-client = { path = "./validators/kafka_client", develop = true }
validators-opensearch-client = { path = "./validators/opensearch_client", develop = true }
validators-config-server = { path = "./validators/config_server", develop = true }
validators-cve-catalog = { path = "./validators/cve_catalog", develop = true }
validators-livepatch-pro-airgapped-server = { path = "./validators/livepatch_pro_airgapped_server", develop = true }
validators-azure-storage = { path = "./validators/azure_storage", develop = true }
validators-parca-store = { path = "./validators/parca_store", develop = true }
validators-parca-scrape = { path = "./validators/parca_scrape", develop = true, extras = ["dev"] }
validators-external-provider = { path = "./validators/external_provider", develop = true }
validators-http-interface = { path = "./validators/http_interface", develop = true }
validators-grafana-dashboard = { path = "./validators/grafana_dashboard", develop = true }
validators-grafana-datasource = { path = "./validators/grafana_datasource", develop = true, extras = ["dev"] }
validators-ingress = { path = "./validators/ingress", develop = true }
validators-prometheus-remote-write = { path = "./validators/prometheus_remote_write", develop = true }
validators-certificate-transfer = { path = "./validators/certificate_transfer", develop = true, extras = ["dev"] }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.5"
bandit = "^1.7.9"
pytest-cov = "^6.2.1"
mypy = "^1.19.0"
types-pyyaml = "^6.0.12.20250915"
types-requests = "^2.32.4.20250913"
yamlfix = ">=1.8.0,<2.0.0"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]

[tool.pytest.ini_options]
timeout = 14400

log_cli = true
log_cli_level = "INFO"
log_format = "%(levelname)s %(message)s"

addopts = "--tb=short"

junit_family = "legacy"
junit_logging = "log"
junit_log_passing_tests = true
junit_duration_report = "total"

[tool.bandit.assert_used]
skips = ['charm_integration_testing/test_suite/*']

[tool.yamlfix]
sequence_style = "keep_style"
preserve_quotes = true

[tool.mypy]
python_version = "3.10"
plugins = ['pydantic.mypy']
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
show_error_codes = true
disable_error_code = ["untyped-decorator", "method-assign", "call-arg"]
