---
name: Setup Kubernetes
description: Setup A kubernetes environment for charm qa
inputs:
  kubeconfig:
    description: Kubeconfig content for the Kubernetes cluster.
    required: true
  kubeconfig_path:
    description: Path to write the kubeconfig file to.
    required: false
    default: ''
  cloud-name:
    description: Name to register the Juju cloud under.
    required: true
outputs:
  cloud-name:
    description: Name of the cloud created and bootstrapped to
    value: ${{ inputs.cloud-name }}
  kubeconfig_path:
    description: Path to kubeconfig file
    value: ${{ inputs.kubeconfig_path || format('/home/ubuntu/.kube/{0}.config', inputs.cloud-name) }}
runs:
  using: composite
  steps:
    - name: Setup Kubeconfig
      env:
        KUBECONFIG_CONTENT: ${{ inputs.kubeconfig }}
        KUBECONFIG_PATH: ${{ inputs.kubeconfig_path || format('/home/ubuntu/.kube/{0}.config', inputs.cloud-name) }}
      shell: bash
      run: |-
        mkdir -p $HOME/.kube
        echo "${KUBECONFIG_CONTENT}" > "${KUBECONFIG_PATH}"
