name: Patch test execution
description: Modify a test execution on Test Observer

inputs:
  test_observer_api:
    description: "URL for the Test Observer API"
    required: True
  test_observer_token:
    description: "Bearer token to send as Authorization header"
    required: True
  test_execution_id:
    description: "ID for the Test Execution"
    required: True

  status:
    description: "Test execution status"
    required: False
    default: "null"
    # type: choice
    # options:
    #   - "NOT_STARTED"
    #   - "IN_PROGRESS"
    #   - "PASSED"
    #   - "FAILED"
    #   - "NOT_TESTED"
    #   - "ENDED_PREMATURELY"
    #   - "COMPLETED"
    #   - ""

  # logs_link:
  #   description: "Link to test logs"

  ci_link:
    description: "Link to CI"
    required: False
    default: "null"

runs:
  using: "composite"
  steps:
    - name: Get Test Observer JSON
      id: request-body
      shell: bash
      env:
        status: ${{ inputs.status }}
        ci_link: ${{ inputs.ci_link }}
      run: |
        jq --null-input --compact-output \
          --arg status "${status}" \
          --arg ci_link "${ci_link}" \
        '
          {
            "status": (if $status != "null" then $status else null end),
            "ci_link": (if $ci_link != "null" then $ci_link else null end)
          } | with_entries(select(.value != null))
        ' > body.json
        echo "file=$(realpath body.json)" >> "$GITHUB_OUTPUT"

    - name: Send request to Test Observer
      uses: ./.github/actions/test-observer/call-api
      id: call-api
      with:
        test_observer_api: "${{ inputs.test_observer_api }}/v1/test-executions/${{ inputs.test_execution_id }}"
        test_observer_token: "${{ inputs.test_observer_token }}"
        method_type: "PATCH"
        request_body: "@${{ steps.request-body.outputs.file }}"

    - name: Echo Action
      shell: bash
      env:
        GITHUB_ACTION: ${{ github.action }}
      run: |
        echo "GITHUB_ACTION: ${GITHUB_ACTION}"

    - name: Debug Sleep
      if: ${{ env.DEBUG_ENABLED == 'true' && github.action == env.DEBUG_SLEEP_AFTER_STEP_ID }}
      shell: bash
      run: |
        echo "Sleeping to assist with debugging."
        sleep $((60*60*4)) # Sleep for 4 hours