---
name: Setup Openstack
description: Setup an Openstack environment for charm qa
inputs:
  novarc:
    description: Novarc content for the OpenStack cloud.
    required: true
  cloud-name:
    description: Name to register the Juju cloud under.
    required: true
outputs:
  cloud-name:
    description: Name of the cloud created and bootstrapped to
    value: ${{ inputs.cloud-name }}
  cloud-definition-path:
    description: Path to the cloud definition YAML file written to disk.
    value: ${{ steps.paths.outputs.cloud-definition-path }}
  credentials-path:
    description: Path to the credentials YAML file written to disk.
    value: ${{ steps.paths.outputs.credentials-path }}
runs:
  using: composite
  steps:
    - name: Report file paths
      id: paths
      shell: bash
      run: |
        echo "cloud-definition-path=${HOME}/openstack/openstack-cloud.yaml" >> "$GITHUB_OUTPUT"
        echo "credentials-path=${HOME}/openstack/openstack-credentials.yaml" >> "$GITHUB_OUTPUT"
    - name: Setup Novarc
      env:
        NOVARC_CONTENT: ${{ inputs.novarc }}
      shell: bash
      run: |
        mkdir -p $HOME/openstack
        echo "${NOVARC_CONTENT}" > $HOME/openstack/novarc
    - name: Setup Image Metadata
      shell: bash
      run: |
        sudo snap install openstack
        source $HOME/openstack/novarc
        openstack image list -f json | jq -r '.[] | select((.Name | test("focal|jammy|noble") and test("amd64") ) and .Status == "active") | .ID' | while read -r id; do
          juju metadata generate-image -a amd64 -i ${id} -r ${OS_REGION_NAME} -u ${OS_AUTH_URL} -d /home/ubuntu/openstack
        done
    - name: Create Openstack cloud files
      env:
        CLOUD: ${{ inputs.cloud-name }}
      shell: bash
      run: |-
        source $HOME/openstack/novarc
        cat >> $HOME/openstack/openstack-cloud.yaml << EOF
        clouds:
          ${CLOUD}:
            type: openstack
            auth-types: [access-key, userpass]
            regions:
              ${OS_REGION_NAME}:
                endpoint: ${OS_AUTH_URL}
        EOF
        cat >> $HOME/openstack/openstack-credentials.yaml << EOF
        credentials:
          ${CLOUD}:
            default-region: ${OS_REGION_NAME}
            ${OS_PROJECT_NAME}:
              auth-type: userpass
              domain-name: ''
              password: ${OS_PASSWORD}
              project-domain-name: ${OS_PROJECT_DOMAIN_NAME}
              tenant-name: ${OS_PROJECT_NAME}
              user-domain-name: ${OS_USER_DOMAIN_NAME}
              username: ${OS_USERNAME}
        EOF
