---
name: Setup Openstack
description: Setup an Openstack environment for charm qa
inputs:
  environment:
    description: Environment to setup the o7k for
    required: true
  controller:
    description: Name of the controller to create
    required: true
  model:
    description: Name of the model to create
    required: true
outputs:
  cloud-name:
    description: Name of the cloud created and bootstrapped to
    value: ${{ steps.cloud.outputs.cloud-name }}
runs:
  using: composite
  steps:
    - name: Setup Novarc
      env:
        environment: ${{ inputs.environment }}
      shell: bash
      run: |
        mkdir -p $HOME/openstack
        if [ "${environment}" = "production" ]; then
          echo "${{ env.o7kprod }}" > $HOME/openstack/novarc
        else
          echo "${{ env.o7kstg }}" > $HOME/openstack/novarc
        fi
    - name: Setup Image Metadata
      shell: bash
      run: |
        sudo snap install openstack
        source $HOME/openstack/novarc
        openstack image list -f json | jq -r '.[] | select((.Name | test("focal|jammy|noble") and test("amd64") ) and .Status == "active") | .ID' | while read -r id; do
          juju metadata generate-image -a amd64 -i ${id} -r ${OS_REGION_NAME} -u ${OS_AUTH_URL} -d /home/ubuntu/openstack
        done
    - name: Add Openstack
      shell: bash
      id: cloud-setup
      run: |
        source $HOME/openstack/novarc
        CLOUD="openstack-machine-env"
        cat >> $HOME/openstack/openstack-cloud.yaml << EOF
        clouds:
          ${CLOUD}:
            type: openstack
            auth-types: [access-key, userpass]
            regions:
              ${OS_REGION_NAME}:
                endpoint: ${OS_AUTH_URL}
        EOF
        cat >> $HOME/openstack/openstack-credentials.yaml << EOF
        credentials:
          ${CLOUD}:
            default-region: ${OS_REGION_NAME}
            ${OS_PROJECT_NAME}:
              auth-type: userpass
              domain-name: ''
              password: ${OS_PASSWORD}
              project-domain-name: ${OS_PROJECT_DOMAIN_NAME}
              tenant-name: ${OS_PROJECT_NAME}
              user-domain-name: ${OS_USER_DOMAIN_NAME}
              username: ${OS_USERNAME}
        EOF
        juju add-cloud $CLOUD $HOME/openstack/openstack-cloud.yaml --client
        juju add-credential $CLOUD -f $HOME/openstack/openstack-credentials.yaml --client
        echo "cloud-name=${CLOUD}" >> $GITHUB_OUTPUT
    - name: Set extra-options
      shell: bash
      id: extra-options
      run: echo "extra-options=--metadata-source $HOME/openstack/images" >> $GITHUB_OUTPUT
