# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "charm-integration-testing"
version = "0.0.0"
description = "A collection of Pytest-based tests for Charm Integration Testing, focusing on validating the deployment and interoperability of charms."
authors = [
    {name = "Ryan Britton",email = "ryan.britton@canonical.com"}
]
requires-python = ">=3.10"

dependencies = [
    "pytest==9.0.3",
    "pydantic (>=2.11.3,<3.0.0)",
    "pyyaml==6.0.2",
    "pytest-timeout==2.3.1",
    "requests (>=2.32.3,<2.35.0)",
    "tenacity (>=9.0.0,<10.0.0)",
    "jubilant (>=1.6.0,<2.0.0)",
    "validators-base",
    "validators-runner",
    "kubernetes (>=32.0.0, < 33.0.0)",
]

[tool.poetry]
packages = [
    { include = "extensions" },
    { include = "juju" },
    { include = "juju_cmd" },
    { include = "juju_jubilant" },
    { include = "kubernetes_client" },
    { include = "resource_registry" },
    { include = "serializeable_dataclass" },
    { include = "test_suite" },
    { include = "utils" },
    { include = "test_observer_client" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
