---
name: Post events to Test Observer
description: Post a timestamped event to the Test Observer API for the given job UUID.
inputs:
  test_observer_api:
    description: Base URL of the Test Observer API
    required: true
  test_observer_token:
    description: Bearer token to send as Authorization header
    required: true
  test_execution_id:
    description: The unique identifier for the test execution (e.g., test execution
      id).
    required: true
  job_uuid:
    description: The unique job identifier (e.g., env/test_execution_id) used in Test
      Observer.
    required: true
  event_name:
    description: The event name to be posted (e.g., job_start, test_end).
    required: true
  detail:
    description: The context of the event.
    required: true
runs:
  using: composite
  steps:
    - name: Get Test Observer JSON
      id: request-body
      shell: bash
      env:
        event_name: ${{ inputs.event_name }}
        detail: ${{ inputs.detail }}
      run: |
        jq --null-input --compact-output \
          --arg event_name "${event_name}" \
          --arg detail "${detail}" \
          --arg timestamp "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
        '
          {
            "events": [
              {
                "event_name": $event_name,
                "detail": $detail,
                "timestamp": $timestamp
              }
            ]
          }
        ' > body.json
        echo "file=$(realpath body.json)" >> "$GITHUB_OUTPUT"
    - name: Send request to Test Observer
      uses: ./.github/actions/test-observer/call-api
      id: call-api
      with:
        test_observer_api: ${{ inputs.test_observer_api }}/v1/test-executions/${{
          inputs.test_execution_id }}/status_update
        test_observer_token: ${{ inputs.test_observer_token }}
        method_type: POST
        request_body: '@${{ steps.request-body.outputs.file }}'
