name: Trigger a rerun on Test Observer
description: Posts a rerun request for the Test Execution ID on Test Observer

inputs:
  test_observer_api:
    description: "URL for the Test Observer API"
    required: True

  test_execution_id:
    description: "ID for the Test Execution to trigger a rerun for"
    required: True

runs:
  using: "composite"
  steps:
    - id: get-json-body
      name: Get Test Observer JSON
      shell: bash
      env:
        test_execution_id: ${{ inputs.test_execution_id }}
      run: |
        jq --null-input --compact-output --arg test_execution_id "${test_execution_id}" '
          {
            "test_execution_ids": [$test_execution_id] 
          }
        ' > body.json
        cat body.json

    - name: Send POST request to Test Observer
      shell: bash
      env:
        test_observer_api: ${{ inputs.test_observer_api }}
      run: |
        curl --fail-with-body \
          --retry 10 \
          -X POST "${test_observer_api}/v1/test-executions/reruns" \
          -H "Content-Type: application/json" \
          -d @body.json
