# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "validators-kyuubi-client"
version = "0.1.0"
description = "Persistence validator for the kyuubi_client interface"
authors = [
    {name = "SQA Team", email = "solutionsqa@canonical.com"}
]

requires-python = ">=3.10"
dependencies = [
    "PyHive[hive_pure_sasl]>=0.7.0,<0.8.0",
    "thrift>=0.16.0,<1.0.0",
    "thrift-sasl>=0.4.3,<0.5.0",
    "validators-base",
]

[project.optional-dependencies]
dev = [
    "validators-test-utils",
]

[project.entry-points."endpoint_persistence_validators"]
kyuubi_client = "validators.kyuubi_client:KyuubiClientPersistenceValidator"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["validators.kyuubi_client"]

[tool.setuptools.package-dir]
"validators.kyuubi_client" = "."
