---
environments:
  # PS6 PROD KUBERNETES
  ps6-sqa-prod_charm_qa_kubernetes-1: &ps6-sqa-prod_charm_qa_kubernetes
    github-runner: ps5-sqa-runners
    platform: kubernetes
    cloud-type: k8s
    kubeconfig-secret: PROD_SQA_KUBECONFIG
    arch: amd64
    bootstrap-config: {}
    bootstrap-constraints:
      root-disk: '5G'
    model-config:
      logging-config: "DEBUG"
      update-status-hook-interval: "2m"
      juju-http-proxy: "http://squid.internal:3128"
      juju-https-proxy: "http://squid.internal:3128"
      juju-no-proxy: "127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com,.svc.cluster.local"
  ps6-sqa-prod_charm_qa_kubernetes-2: *ps6-sqa-prod_charm_qa_kubernetes
  ps6-sqa-prod_charm_qa_kubernetes-3: *ps6-sqa-prod_charm_qa_kubernetes
  ps6-sqa-prod_charm_qa_kubernetes-4: *ps6-sqa-prod_charm_qa_kubernetes
  ps6-sqa-prod_charm_qa_kubernetes-5: *ps6-sqa-prod_charm_qa_kubernetes
  ps6-sqa-prod_charm_qa_kubernetes-6: *ps6-sqa-prod_charm_qa_kubernetes
  # PS6 STG KUBERNETES
  ps6-sqa-stg_charm_qa_kubernetes-1: &ps6-sqa-stg_charm_qa_kubernetes
    github-runner: ps5-sqa-runners
    platform: kubernetes
    cloud-type: k8s
    kubeconfig-secret: STG_SQA_KUBECONFIG
    arch: amd64
    bootstrap-config: {}
    bootstrap-constraints:
      root-disk: '5G'
    model-config:
      logging-config: "DEBUG"
      update-status-hook-interval: "2m"
      juju-http-proxy: "http://squid.internal:3128"
      juju-https-proxy: "http://squid.internal:3128"
      juju-no-proxy: "127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com,.svc.cluster.local"
  ps6-sqa-stg_charm_qa_kubernetes-2: *ps6-sqa-stg_charm_qa_kubernetes
  # PS6 PROD OPENSTACK
  ps6-sqa-prod_charm_qa_openstack-1: &ps6-sqa-prod_charm_qa_openstack
    github-runner: ps5-sqa-runners
    platform: machine
    cloud-type: o7k
    novarc-secret: PROD_SQA_NOVARC
    arch: amd64
  ps6-sqa-prod_charm_qa_openstack-2: *ps6-sqa-prod_charm_qa_openstack
  # PS7 PROD KUBERNETES
  ps7-sqa-prod_charm_qa_kubernetes-1: &ps7-sqa-prod_charm_qa_kubernetes
    github-runner: ps7-sqa-runners
    platform: kubernetes
    cloud-type: k8s
    kubeconfig-secret: PROD_PS7_KUBECONFIG
    arch: amd64
    bootstrap-config:
      apt-http-proxy: "http://egress.ps7.internal:3128"
      apt-https-proxy: "http://egress.ps7.internal:3128"
      http-proxy: "http://egress.ps7.internal:3128"
      https-proxy: "http://egress.ps7.internal:3128"
      no-proxy: "127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com,.svc.cluster.local"
      snap-http-proxy: "http://egress.ps7.internal:3128"
      snap-https-proxy: "http://egress.ps7.internal:3128"
    bootstrap-constraints: &ps7-model-constraints
      root-disk: '5G'
    model-config: &ps7-model-config
      logging-config: "DEBUG"
      update-status-hook-interval: "2m"
      juju-http-proxy: "http://egress.ps7.internal:3128"
      juju-https-proxy: "http://egress.ps7.internal:3128"
      juju-no-proxy: "127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.canonical.com,.launchpad.net,.internal,.jujucharms.com,.svc.cluster.local"
      snap-http-proxy: "http://egress.ps7.internal:3128"
      snap-https-proxy: "http://egress.ps7.internal:3128"
  ps7-sqa-prod_charm_qa_kubernetes-2: *ps7-sqa-prod_charm_qa_kubernetes
  # PS7 PROD OPENSTACK
  ps7-sqa-prod_charm_qa_openstack-1: &ps7-sqa-prod_charm_qa_openstack
    github-runner: ps7-sqa-runners
    platform: machine
    cloud-type: o7k
    novarc-secret: PROD_PS7_NOVARC
    arch: amd64
    bootstrap-config:
      apt-http-proxy: "http://egress.ps7.internal:3128"
      apt-https-proxy: "http://egress.ps7.internal:3128"
      http-proxy: "http://egress.ps7.internal:3128"
      https-proxy: "http://egress.ps7.internal:3128"
      no-proxy: "127.0.0.1,localhost,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.internal,.svc.cluster.local"
      snap-http-proxy: "http://egress.ps7.internal:3128"
      snap-https-proxy: "http://egress.ps7.internal:3128"
    bootstrap-constraints: *ps7-model-constraints
    model-config: *ps7-model-config
  ps7-sqa-prod_charm_qa_openstack-2: *ps7-sqa-prod_charm_qa_openstack
