# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "validators-grafana-dashboard"
version = "0.1.0"
description = "Validator for grafana_dashboard interface"
authors = [
    {name = "SQA Team", email = "solutionsqa@canonical.com"}
]

requires-python = ">=3.10"
dependencies = [
    "validators-base",
]

[project.entry-points."endpoint_validators"]
grafana_dashboard = "validators.grafana_dashboard:GrafanaDashboardValidator"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["validators.grafana_dashboard"]

[tool.setuptools.package-dir]
"validators.grafana_dashboard" = "."
