# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "validators-runner"
version = "0.1.0"
description = "Runs endpoint validators"
authors = [
    {name = "SQA Team", email = "solutionsqa@canonical.com"}
]

requires-python = ">=3.10"
dependencies = [
    "ops>=3.3.0,<4.0.0",
    "pydantic>=2.0.0",
    "validators-base",
    "validators-s3",
    "validators-postgresql-client",
    "validators-tracing[deep]",
    "validators-loki-push-api",
    "validators-object-storage",
    "validators-prometheus-scrape",
    "validators-kafka-client",
    "validators-temporal-host-info",
    "validators-config-server",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["validators.runner"]

[tool.setuptools.package-dir]
"validators.runner" = "."

[project.scripts]
run_validators = "validators.runner.runner:main"
