---
name: Run Charm Tests and Assert Passed
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      target_environment:
        type: string
        required: true
      target_charm:
        type: string
        required: true
      target_endpoint:
        type: string
        required: true
      target_revision:
        type: string
        required: true
      target_base:
        type: string
        required: true
      target_track:
        type: string
        required: true
      target_risk:
        type: string
        required: true
      neighbor_charm:
        type: string
        required: true
      neighbor_endpoint:
        type: string
        required: true
    secrets:
      STG_TEST_OBSERVER_TOKEN:
        required: true
jobs:
  run-charm-tests-and-assert-pass:
    runs-on: [self-hosted-linux-amd64-jammy-solqa-ps7]
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Create Test Execution
        id: create-test-execution
        uses: ./.github/actions/test-observer/create-test-execution
        with:
          test_observer_api: ${{ vars.STG_TEST_OBSERVER_API }}
          test_observer_token: ${{ secrets.STG_TEST_OBSERVER_TOKEN }}
          charm: ${{ inputs.target_charm }}
          revision: ${{ inputs.target_revision }}
          arch: charm-testing-integration-test-assert-pass-arch
          environment: charm-testing-integration-test-assert-pass-environment
          test_plan: charm-testing-integration-test-assert-pass-test_plan
          track: ${{ inputs.target_track }}
          risk: ${{ inputs.target_risk }}
          status: NOT_STARTED
      - name: Trigger Charm Tests
        id: trigger-charm-tests
        uses: ./.github/actions/workflow-dispatch
        with:
          workflow: charm-testing.yaml
          ref: ${{ github.head_ref || github.ref_name }}
          inputs: |
            {
              "test_observer_environment": "staging",
              "target_environment": "${{ inputs.target_environment }}",
              "charm_under_test": "${{ inputs.target_charm }}",
              "charm_endpoint": "${{ inputs.target_endpoint }}",
              "execution_id": "${{ steps.create-test-execution.outputs.test_execution_id }}",
              "juju_channel": "3/stable",
              "neighbor": "${{ inputs.neighbor_charm }}",
              "neighbor_endpoint": "${{ inputs.neighbor_endpoint }}",
              "revision": "${{ inputs.target_revision }}",
              "series": "${{ inputs.target_base }}",
              "channel": "${{ inputs.target_track }}/${{ inputs.target_risk }}"
            }
      - name: Ensure Charm Tests Workflow Success
        shell: bash
        env:
          workflow_conclusion: ${{ steps.trigger-charm-tests.outputs.conclusion }}
        run: |
          echo "GitHub Workflow Conclusion is '$workflow_conclusion'"
          if [[ "$workflow_conclusion" != "success" ]]
          then
            echo "Failing workflow since charm tests workflow failed"
            exit 1
          fi
      - name: Get Test Execution
        id: get-test-execution
        uses: ./.github/actions/test-observer/get-test-execution
        with:
          test_observer_api: ${{ vars.STG_TEST_OBSERVER_API }}
          test_observer_token: ${{ secrets.STG_TEST_OBSERVER_TOKEN }}
          test_execution_id: ${{ steps.create-test-execution.outputs.test_execution_id }}
      - name: Ensure Test Execution Passed
        shell: bash
        env:
          test_execution_status: ${{ steps.get-test-execution.outputs.test_execution_status }}
        run: |
          echo "Test Execution Status is '$test_execution_status'"
          if [[ "$test_execution_status" != "PASSED" ]]
          then
            echo "Failing workflow since tests did not pass"
            exit 1
          fi
      - name: Ensure Test Execution Metadata Posted
        shell: bash
        env:
          test_execution_metadata: ${{ steps.get-test-execution.outputs.test_execution_metadata }}
        run: |-
          echo "Test Execution Metadata is:"
          echo "$test_execution_metadata" | jq
          if ! echo "$test_execution_metadata" | jq --exit-status 'has("charm_qa:charm")' > /dev/null
          then
            echo "Failing workflow since execution metadata does not contain expected category 'charm_qa:charm'"
            exit 1
          fi
