name: Trigger Charm Tests
run-name: "Testing ${{ inputs.charm_under_test }}:${{ inputs.charm_endpoint }} against ${{ inputs.neighbor }}:${{ inputs.neighbor_endpoint }}. (environment: ${{ inputs.environment }}${{ inputs.execution_id != '' && ', test execution: ' || '' }}${{ inputs.execution_id }})"

permissions:
  contents: read # only needed for private repos

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run in."
        type: choice
        default: testing
        options:
          - testing
          - staging
          - production
      # TODO SQT-452: GitHub workflow_dispatch is limited to 10 inputs
      # But maybe by the time we need this that will have changed!
      # https://github.com/orgs/community/discussions/8774
      # If not, maybe pass in JSON and use fromJSON()
      # arch:
      #   description: "Architecture of the charms being tested."
      #   required: false
      #   type: choice
      #   options:
      #     - amd64
      #   default: amd64
      charm_under_test:
        description: "charmhub.io name of the primary charm under test"
        required: true
      charm_endpoint:
        description: "Endpoint of the charm being tested."
        required: true
      execution_id:
        description: "Test Observer execution ID to post results from this test to."
        required: false
      juju_channel:
        description: "Juju channel to use while testing."
        required: false
        default: "3/stable"
      neighbor:
        description: "charmhub.io name of the charm to test the primary charm against."
        required: true
      neighbor_endpoint:
        description: "Endpoint for the neighbor charm being tested."
        required: true
      revision:
        description: "Revision number of the charm under test."
        required: true
      series:
        description: "Series to run the charm tests under."
        required: false
        type: choice
        options:
          - "20.04"
          - "22.04"
          - "24.04"
        default: 24.04
      substrate:
        description: "Substrate to run the tests on."
        required: false
        type: choice
        options:
          - kubernetes
        default: kubernetes
jobs:
  run-charm-tests:
    name: Run Charm Tests
    uses: ./.github/workflows/run-charm-tests.yaml
    with:
      environment: ${{ inputs.environment }}
      arch: amd64
      charm_under_test: ${{ inputs.charm_under_test }}
      charm_endpoint: ${{ inputs.charm_endpoint }}
      execution_id: ${{ inputs.execution_id }}
      juju_channel: ${{ inputs.juju_channel }}
      neighbor: ${{ inputs.neighbor }}
      neighbor_endpoint: ${{ inputs.neighbor_endpoint }}
      revision: ${{ inputs.revision }}
      series: ${{ inputs.series }}
      substrate: ${{ inputs.substrate }}
    secrets:
      PROD_SQA_KUBECONFIG: ${{ secrets.PROD_SQA_KUBECONFIG }}
      STG_SQA_KUBECONFIG: ${{ secrets.STG_SQA_KUBECONFIG }}
      SWIFT_OS_AUTH_URL: ${{ secrets.SWIFT_OS_AUTH_URL }}
      SWIFT_OS_USERNAME: ${{ secrets.SWIFT_OS_USERNAME }}
      SWIFT_OS_PASSWORD: ${{ secrets.SWIFT_OS_PASSWORD }}
      SWIFT_OS_PROJECT_NAME: ${{ secrets.SWIFT_OS_PROJECT_NAME }}
      SWIFT_OS_REGION_NAME: ${{ secrets.SWIFT_OS_REGION_NAME }}
      SWIFT_OS_USER_DOMAIN_NAME: ${{ secrets.SWIFT_OS_USER_DOMAIN_NAME }}
      SWIFT_OS_PROJECT_DOMAIN_NAME: ${{ secrets.SWIFT_OS_PROJECT_DOMAIN_NAME }}
