name: Execute tests against two charms and their integrations
run-name: Testing ${{ github.event.inputs.charm_under_test }}:${{ github.event.inputs.charm_endpoint }} against ${{ github.event.inputs.neighbor }}:${{ github.event.inputs.neighbor_endpoint }}${{ github.event.inputs.execution_id != '' && ' for the ' || '' }}${{ github.event.inputs.execution_id }}${{ github.event.inputs.execution_id != '' && ' test' || '' }}.

concurrency:
  group: ${{ (inputs.environment == 'production' || inputs.environment == 'staging') && 'production-k8s' || 'staging-k8s' }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run in."
        type: choice
        default: testing
        options:
          - testing
          - staging
          - production
      arch:
        description: "Architecture of the charms being tested."
        required: false
        type: choice
        options:
          - amd64
        default: amd64
      charm_under_test:
        description: "charmhub.io name of the primary charm under test"
        required: true
      charm_endpoint:
        description: "Endpoint of the charm being tested."
        required: true
      execution_id:
        description: "Test Observer execution ID to post results from this test to."
        required: false
      juju_channel:
        description: "Juju channel to use while testing."
        required: false
        default: "3/stable"
      neighbor:
        description: "charmhub.io name of the charm to test the primary charm against."
        required: true
      neighbor_endpoint:
        description: "Endpoint for the neighbor charm being tested."
        required: true
      revision:
        description: "Revision number of the charm under test."
        required: true
      series:
        description: "Series to run the charm tests under."
        required: false
        type: choice
        options:
          - "20.04"
          - "22.04"
          - "24.04"
        default: 24.04
      # TODO SQT-452: GitHub workflow_dispatch is limited to 10 inputs
      # But maybe by the time we need this that will have changed!
      # https://github.com/orgs/community/discussions/8774
      # If not, maybe pass in JSON and use fromJSON()
      # substrate:
      #   description: "Substrate to run the tests on."
      #   required: false
      #   type: choice
      #   options:
      #     - kubernetes
      #   default: kubernetes
jobs:
  execute-charm-test:
    name: Execute integration tests against the charms
    runs-on:
      - self-hosted
      - charm_qa
    env:
      test_observer_api: ${{ github.event.inputs.environment == 'production' && vars.PROD_TEST_OBSERVER_API || (github.event.inputs.environment == 'staging' && vars.STG_TEST_OBSERVER_API || '') }}
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4
    - name: Report Test Execution Start To Test Observer
      if: ${{ always() && env.test_observer_api != '' && github.event.inputs.execution_id != '' }}
      uses: ./.github/actions/patch-test-execution
      with:
        test_observer_api: ${{ env.test_observer_api }}
        test_execution_id: ${{ github.event.inputs.execution_id }}
        status: "IN_PROGRESS"
    - name: Setup Kubeconfig
      shell: bash
      run: |
        mkdir -p $HOME/.kube
        if [ "${{ github.event.inputs.environment }}" = "production" ] || [ "${{ github.event.inputs.environment }}" = "staging" ]; then
          echo '${{ secrets.PROD_SQA_KUBECONFIG }}' > $HOME/.kube/config
        else        
          echo '${{ secrets.STG_SQA_KUBECONFIG }}' > $HOME/.kube/config
        fi
    - name: Install Juju
      shell: bash
      run: |
        sudo snap install juju --channel ${{ github.event.inputs.juju_channel }}
        sudo snap install juju-wait --classic
    - name: Install Repository
      shell: bash
      run: |
        sudo apt-get update --quiet
        sudo apt-get install pipx --quiet --assume-yes
        sudo tee /etc/pip.conf <<EOF
        [global]
        proxy= http://squid.internal:3128
        EOF
        pipx install poetry==2.0
        HTTPS_PROXY="http://squid.internal:3128" poetry install
    - name: Add K8s
      shell: bash
      run: |
        KUBECONFIG="$HOME/.kube/config" juju add-k8s ps6 --client
    - name: Bootstrap Controller
      id: controller
      shell: bash
      run: |
        date=$(date +"%y-%m-%d-%H-%M-%S")
        # juju will prefix the namespace with "controller"
        juju bootstrap ps6 --bootstrap-constraints root-disk=5G $date
        echo "date=$date" >> $GITHUB_OUTPUT
    - name: Create Model
      shell: bash
      run: |
        juju add-model model-${{ steps.controller.outputs.date }} --config "logging-config=DEBUG"
    - name: Deploy Bundles
      continue-on-error: true
      shell: bash
      run: |
        ./scripts/test-deploy.sh \
          --model model-${{ steps.controller.outputs.date }} \
          --bundles ./static/bundles/${{ github.event.inputs.charm_under_test }}.yaml ./static/bundles/${{ github.event.inputs.neighbor }}.yaml \
          --integrations "${{ github.event.inputs.charm_under_test }}:${{ github.event.inputs.charm_endpoint }}/${{ github.event.inputs.neighbor }}:${{ github.event.inputs.neighbor_endpoint }}" \
          --junit-xml=junit-deploy.xml
    - name: Execute Tests
      continue-on-error: true
      shell: bash
      run: |
        ./scripts/test-integration.sh \
          --model model-${{ steps.controller.outputs.date }} \
          --target-application ${{ github.event.inputs.charm_under_test }} \
          --target-endpoint ${{ github.event.inputs.charm_endpoint }} \
          --neighbor-application ${{ github.event.inputs.neighbor }} \
          --neighbor-endpoint ${{ github.event.inputs.neighbor_endpoint }} \
          --junit-xml=junit-integration.xml
    - name: Teardown charm under test
      continue-on-error: true
      shell: bash
      run: |
        ./scripts/test-teardown.sh \
          --model model-${{ steps.controller.outputs.date }} \
          --applications ${{ github.event.inputs.charm_under_test }} \
          --junit-xml=junit-teardown.xml
    - name: Merge JUnit output
      shell: bash
      run: |
        ./scripts/merge-junit.sh junit-*.xml junit.xml
        cat junit.xml
    - name: Post results to Test Observer
      if: ${{ env.test_observer_api != '' && github.event.inputs.execution_id != '' }}
      uses: ./.github/actions/post-results
      with:
        test_observer_api: ${{ env.test_observer_api }}
        test_execution_id: ${{ github.event.inputs.execution_id }}
        junit_xml: ./junit.xml
    - name: Setup Logs directory
      if: ${{ always() }}
      shell: bash
      run: mkdir -p $HOME/logs
    - name: Collect Logs
      if: ${{ always() }}
      uses: canonical/juju-k8s-crashdump/actions/juju-k8s-crashdump@main
      with:
        kubeconf: $HOME/.kube/config
        controller: ${{ steps.controller.outputs.date }}
        output_path: $HOME/logs/juju-logs.tar.gz
        proxy: http://squid.internal:3128
    - name: Add JUnit to logs
      shell: bash
      run: cp ./junit.xml $HOME/logs/
    - name: Post Logs To Swift
      if: ${{ always() && github.event.inputs.execution_id != '' }}
      uses: canonical/sqa-cloud-deployment-pipeline/.github/actions/upload-to-swift@main
      with:
        job_uuid: ${{ github.event.inputs.environment }}/${{ github.event.inputs.execution_id }}
        log_path: $HOME/logs
        swift_bucket: charm-qa
        SWIFT_OS_AUTH_URL: ${{ secrets.SWIFT_OS_AUTH_URL }}
        SWIFT_OS_USERNAME: ${{ secrets.SWIFT_OS_USERNAME }}
        SWIFT_OS_PASSWORD: ${{ secrets.SWIFT_OS_PASSWORD }}
        SWIFT_OS_PROJECT_NAME: ${{ secrets.SWIFT_OS_PROJECT_NAME }}
        SWIFT_OS_REGION_NAME: ${{ secrets.SWIFT_OS_REGION_NAME }}
        SWIFT_OS_USER_DOMAIN_NAME: ${{ secrets.SWIFT_OS_USER_DOMAIN_NAME }}
        SWIFT_OS_PROJECT_DOMAIN_NAME: ${{ secrets.SWIFT_OS_PROJECT_DOMAIN_NAME }}
    - name: Mark Test Execution completed on Test Observer
      if: ${{ always() && env.test_observer_api != '' && github.event.inputs.execution_id != '' }}
      uses: ./.github/actions/patch-test-execution
      with:
        test_observer_api: ${{ env.test_observer_api }}
        test_execution_id: ${{ github.event.inputs.execution_id }}
        status: "COMPLETED"
    - name: Teardown Controller
      if: ${{ always() }}
      shell: bash
      run: |
        timeout 15m juju kill-controller ${{ steps.controller.outputs.date }} --no-prompt
