---
name: Run Integration Tests for Charm Testing
permissions:
  contents: read
on:
  workflow_dispatch:
  workflow_call:
jobs:
  assert-pass:
    strategy:
      max-parallel: 1
      matrix:
        params:
          - target_charm: self-signed-certificates
            target_endpoint: certificates
            target_channel: 1/stable
            target_revision: 588
            target_base: '22.04'
            neighbor_charm: postgresql-k8s
            neighbor_endpoint: certificates
            substrate: kubernetes
    uses: ./.github/workflows/charm-testing-integration-test-assert-pass.yaml
    permissions:
      contents: read
      actions: write
    with:
      target_charm: ${{ matrix.params.target_charm }}
      target_endpoint: ${{ matrix.params.target_endpoint }}
      target_revision: ${{ matrix.params.target_revision }}
      target_base: ${{ matrix.params.target_base }}
      neighbor_charm: ${{ matrix.params.neighbor_charm }}
      neighbor_endpoint: ${{ matrix.params.neighbor_endpoint }}
      substrate: ${{ matrix.params.substrate }}
    secrets:
      STG_TEST_OBSERVER_TOKEN: ${{ secrets.STG_TEST_OBSERVER_TOKEN }}
