name: Clean up K8s environments
run-name: "Cleaning up ${{ inputs.environment }} K8s environment"

permissions:
  contents: read # only needed for private repos

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to clean."
        type: choice
        default: staging
        options:
          - staging
          - production
  workflow_call:
    inputs:
      environment:
        description: "Environment to clean."
        type: string
        required: true
    secrets:
      PROD_SQA_KUBECONFIG:
        required: true
      STG_SQA_KUBECONFIG:
        required: true
jobs:
  cleanup-k8s:
    name: Clean up any leftover K8s artifacts from old Charm QA environments
    runs-on:
      - self-hosted
      - charm_qa
    steps:
      - name: Install kubectl
        shell: bash
        run: sudo snap install kubectl --classic

      - name: Setup kube config
        shell: bash
        env:
          environment: ${{ inputs.environment }}
          production_kubeconfig: ${{ secrets.PROD_SQA_KUBECONFIG }}
          staging_kubeconfig: ${{ secrets.STG_SQA_KUBECONFIG }}
        run: |
          case "$environment" in
            "production") echo "$production_kubeconfig" > "kubeconfig" ;;
            "staging") echo "$staging_kubeconfig" > "kubeconfig" ;;
            *) echo "Unknown environment '$environment'"; exit 1 ;;
          esac
          echo "KUBECONFIG=$(realpath kubeconfig)" >> $GITHUB_ENV

      - name: Remove all model and controller namespaces older than an hour
        shell: bash
        env:
          environment: ${{ inputs.environment }}
        run: |
          kubectl get namespaces --output json | jq --raw-output '
              .items[] | 
              select(.metadata.name | test("^(controller|model)-[0-9]+-[0-9]+$")) |
              select((now - (.metadata.creationTimestamp | fromdateiso8601)) > 3600) |
              .metadata.name
          ' | xargs --no-run-if-empty kubectl delete namespace --timeout=30m
