name: Run Charm Test Suites

on:
  workflow_dispatch:
  push: # TODO remove

jobs:
  run-test-suites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pipx install poetry==1.6
          poetry install

      # Connect to prodstack

      # Bootstrap controller

      # Report test observer started

      - name: Run test suite
        run: |
          ./scripts/run-test-suites.sh

      # Upload results to swift

      # Report test observer results

      # Report weebl results
