# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "validators-grpc"
version = "0.1.0"
description = "Validator for parca_store (gRPC) interface"
authors = [
    {name = "SQA Team", email = "solutionsqa@canonical.com"}
]

requires-python = ">=3.10"
dependencies = [
    "grpcio>=1.60.0",
    "validators-base",
]

[project.entry-points."endpoint_validators"]
parca_store = "validators.grpc:ParcaStoreValidator"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["validators.grpc"]

[tool.setuptools.package-dir]
"validators.grpc" = "."
